apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:

      # ← Add this block to run migrations first
      initContainers:
        - name: migrate
          image: nash11/backend:latest
          imagePullPolicy: Always
          command: ["npx", "knex", "migrate:latest", "--env", "development"]
          # It will pick up DATABASE_URL & NODE_ENV from the same ConfigMap/Secret below
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets

      containers:
        - name: backend
          image: nash11/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets